kind: pipeline
type: docker
name: default

steps:
  # 의존성 체크 및 린트
  - name: lint-and-check
    image: python:3.11-slim
    commands:
      - pip install --no-cache-dir -r requirements.txt
      - python -m py_compile fastapi_mcp_server.py
      - echo "Build check completed successfully"
    when:
      event:
        - push
        - pull_request
        - custom

  # main/master 브랜치에 push 또는 custom 이벤트 시 도커 이미지 빌드 및 푸시
  - name: build-and-push-branch
    image: plugins/docker
    settings:
      registry: ghcr.io
      repo: ghcr.io/jhleee/backlog-mcp-server
      username:
        from_secret: github_username
      password:
        from_secret: github_token
      tags:
        - latest
        - "commit-${DRONE_COMMIT_SHA:0:8}"
        - "${DRONE_BRANCH}"
      dockerfile: Dockerfile
      context: .
    when:
      event:
        - push
        - custom
      branch:
        - master
        - main
    depends_on:
      - lint-and-check

  # 태그 이벤트 발생 시 도커 이미지 빌드 및 푸시
  - name: build-and-push-tag
    image: plugins/docker
    settings:
      registry: ghcr.io
      repo: ghcr.io/jhleee/backlog-mcp-server
      username:
        from_secret: github_username
      password:
        from_secret: github_token
      tags:
        - "${DRONE_TAG}"
        - latest
      dockerfile: Dockerfile
      context: .
    when:
      event:
        - tag
    depends_on:
      - lint-and-check

# 파이프라인 실행 조건
trigger:
  event:
    - push
    - tag
    - pull_request
    - custom
    - promote