kind: pipeline
type: docker
name: default

steps:
  # push 또는 custom 이벤트 발생 시 실행
  - name: build-and-push
    image: plugins/docker
    settings:
      registry: ghcr.io
      repo: ghcr.io/jhleee/backlog-mcp-server
      username:
        from_secret: github_username
      password:
        from_secret: github_token
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:8}
        - ${DRONE_BRANCH}
      # auto_tag가 ${DRONE_BRANCH}와 중복되므로 제거
      # auto_tag: true
      # auto_tag_suffix: ${DRONE_BUILD_NUMBER}
    when:
      # 이 스텝의 실행 조건을 여기에 명시
      event:
        - push
        - custom
      branch: # 브랜치 조건을 스텝 레벨로 이동
        - master
        - main

  # tag 이벤트 발생 시 실행
  - name: build-and-push-tag
    image: plugins/docker
    settings:
      registry: ghcr.io
      repo: ghcr.io/jhleee/backlog-mcp-server
      username:
        from_secret: github_username
      password:
        from_secret: github_token
      tags:
        - ${DRONE_TAG}
        - latest
    when:
      event:
        - tag

# 파이프라인 전체 실행 조건
trigger:
  event:
    - push
    - tag
    - custom
    - promote